### ISSUE TITLE
Update does not work

### ISSUE THREAD

**Issue by sucper** [jonasbark/flutter_in_app_update#70] opened 2021-04-29 06:38 UTC
I created a new project, copied the code from the example.
I created an application project in Google Console, configured it and started internal testing.
Created two .aab (version 1.0.0 + 1 and 1.0.1 + 2)
I got that the "update" button in the google market.
Opened the app and tried to do `InAppUpdate.checkForUpdate ()`

> I/PlayCore: UID: [10900]  PID: [14384] AppUpdateService : requestUpdateInfo(com.sucper.loader)
> I/PlayCore: UID: [10900]  PID: [14384] AppUpdateService : Initiate binding to the service.
> I/PlayCore: UID: [10900]  PID: [14384] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
> I/PlayCore: UID: [10900]  PID: [14384] AppUpdateService : linkToDeath
> I/PlayCore: UID: [10900]  PID: [14384] OnRequestInstallCallback : onRequestInfo
> I/PlayCore: UID: [10900]  PID: [14384] AppUpdateService : Unbind from service..

and 

> checkForUpdate InAppUpdateState{updateAvailability: 1, immediateUpdateAllowed: false, flexibleUpdateAllowed: false, availableVersionCode: 0, installStatus: 0, packageName: com.sucper.loader, clientVersionStalenessDays: null, updatePriority: 0}

i also tried using .apk

**Comment by Saurabh-ss12** [comment] 2021-05-15 13:39
Same is happening in my case

**Comment by him123** [comment] 2021-05-16 06:22
Same things is happening for me as well, author should reply at least

**Comment by rjohannengabriel** [comment] 2021-05-17 08:23
Fixed this by adding the Play Core Library to my app level build.gradle file according to the documentation found in 

https://developer.android.com/guide/playcore

The Play Core Library Triggers the in_app_updates

```gradle
dependencies {
    // This dependency is downloaded from the Google’s Maven repository.
    // So, make sure you also include that repository in your project's build.gradle file.
    implementation 'com.google.android.play:core:1.10.0'

    // For Kotlin users also add the Kotlin extensions library for Play Core:
    implementation 'com.google.android.play:core-ktx:1.8.1'
    ...
}
```

**Comment by sucper** [comment] 2021-05-17 11:21
@rjohannengabriel 
the Play Core library has already been added to the in_app_updates module.
But I tried adding from to build.gradle.

Unfortunately, it didn’t help
Let me know if this helps you. Maybe I'm doing something wrong

**Comment by sucper** [comment] 2021-05-18 05:55
@rjohannengabriel, can you send me a working example?

**Comment by sucper** [comment] 2021-05-18 11:16
I tried to implement in app update using "Channel method".
And I get the same error ...
It looks like a problem in PlayCore itself or there is some condition that I do not know about

**Comment by swarupbhanjachowdhury** [comment] 2021-05-19 16:32
Same, not working

**Comment by him123** [comment] 2021-06-01 12:00
So, I have implemented it before but did not get success to see the in app update dialog in my screen first time when I have run the code from my vs code. 

Then I tried to implement the native in-app android code in native android. It worked then I realise to implement this plugin will be much more easier rather to manage everything by my own.

Then I again implement this plugin again in my flutter code. Here, the second time I came to know this plug in code will not execute the dialog when you run from flutter or android studio but you have to upload your app to the Google Play store to test. I am not asking you guys to publish this version without test but Google provides internal app sharing tool which you can briefly understand here: https://developer.android.com/guide/playcore/in-app-updates/test

although there are some small issue I am facing with dependency but I am getting that in app update dialog but testing my app with internal sharing app tool in Google Play Store.

**Comment by sucper** [comment] 2021-06-07 10:51
@him123 
Have you used native code instead of this plugin?
I uploaded the app to google play for internal testing but it didn't work.
This plugin doesn't work.
You can share your code in which the in-app Update is implemented

**Comment by rjohannengabriel** [comment] 2021-06-07 13:04
@sucper I noticed in-app updates work if Google Play (app) detects that there is an update for your app. This plugin probably (correct me if I'm wrong) uses Google Play services to check if there's any update. If the Google Play app sees it, then your app will too. 

That's just my observation.

**Comment by sucper** [comment] 2021-06-08 09:00
@rjohannengabriel 
I think you are right. But! I have uploaded an internal testing app on the google market. Cleared the play market cache.
I made sure that the "open" button has changed to "update". Did NOT update through the market.

I opened the app and asked for an update check.
Then I decided to wait a few days.
And again I repeated the request from the application itself.
All this time, I had the opportunity to update the application through the Play Store.

In logcat I always get the same message ... (see the first message in this thread)

**Comment by rjohannengabriel** [comment] 2021-06-09 01:46
> @rjohannengabriel
> I think you are right. But! I have uploaded an internal testing app on the google market. Cleared the play market cache.
> I made sure that the "open" button has changed to "update". Did NOT update through the market.
> 
> I opened the app and asked for an update check.
> Then I decided to wait a few days.
> And again I repeated the request from the application itself.
> All this time, I had the opportunity to update the application through the Play Store.
> 
> In logcat I always get the same message ... (see the first message in this thread)

Just to be sure, are you using a physical device or an emulator? Also have you tried other methods from the library (e.g. flexible updates or immediate updates) ?

**Comment by sucper** [comment] 2021-06-10 03:49
@rjohannengabriel
Of course I am using a physical device.
I get an error at the "checkForUpdate" request stage.
But I tried to use other features of the plugin as well. But I received no positive answer.

So again:
1. I am using a physical device
2. I am using the "Google Play" app store
3. I am using internal testing. (but I was releasing a working version)
4. I am using the code provided in the examples section of this plugin.
5. I see the "update" button in Google Play (but I don't click it)
6. I tried to wait a few days.

p.s. I would love to use native code, but my attempt seems to have failed.

**Comment by josephantonyk94** [comment] 2021-06-26 14:51
me also getting updateAvailability: 1,  as status code i been using oppo as the testing device

**Comment by larssn** [comment] 2021-09-14 17:01
We're using the plugin for multiple customers, and channels in Play (internal, alpha, production). Some of our customers cannot download the updates, and I haven't been able to discern a pattern. I, for one, am an internal tester, and it works for me. A customer close by is also an internal tester, and it doesn't work for him.

Same goes for alpha and production. It's weird.

Any insights would be appreciated.

**Comment by shahrukhioux** [comment] 2021-09-24 06:18
Add these  dependency and it will starts working.

    // So, make sure you also include that repository in your project's build.gradle file.
    implementation 'com.google.android.play:core:1.10.2'

    // For Kotlin users also add the Kotlin extensions library for Play Core:
    implementation 'com.google.android.play:core-ktx:1.8.1'

**Comment by FabioClem** [comment] 2021-09-29 20:00
Im facing the same issue
i added the dependency  of play core in build.gradle but aways return 1 in updateAvailability.

any ideia how to solve this? 
thanks

**Comment by DonWasyl** [comment] 2022-03-07 15:25
I have a similar problem. `availableVersionCode` always return version which I deployed... one year ago... :/

**Comment by clickervinod** [comment] 2022-03-22 19:48
i had also faced this problem.
it worked when i clear that cache of  play store.

but the problem is not all users will do this. What is the solutions??

**Comment by jonasbark** [comment] 2022-04-02 08:34
Closing this due to the fact that all this plugin does is relay information from the official google library. The plugin has no way to improve or alter results.

More information can be found in https://developer.android.com/guide/playcore/in-app-updates

**Closed by jonasbark** 2022-04-02 08:34 UTC
