### ISSUE TITLE
Crash found on Firebase Crashlytics on a user device

### ISSUE THREAD

**Issue by ycv005** [jonasbark/flutter_in_app_update#59] opened 2021-02-03 18:49 UTC
Flutter version- 1.22.5

Hey there, thanks for the plugin. I am here to report a Crash which has effected my 3 users in last 24 hrs. Please @jonasbark @mig35 solve the issue.

Here is the highlighted error mentioned in the firebase crashlytics-

```
InAppUpdatePlugin.java line 37
de.ffuf.in_app_update.InAppUpdatePlugin$onActivityResumed$1.a
```

```
Fatal Exception: java.lang.RuntimeException
java.lang.reflect.InvocationTargetException
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:451)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)
Caused by java.lang.reflect.InvocationTargetException
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)
Caused by android.content.IntentSender$SendIntentException
android.app.Activity.startIntentSenderForResultInner (Activity.java:4878)
com.google.android.play.core.appupdate.e.a (e.java:9)
de.ffuf.in_app_update.InAppUpdatePlugin$onActivityResumed$1.a (InAppUpdatePlugin.java:37)
de.ffuf.in_app_update.InAppUpdatePlugin$onActivityResumed$1.a (InAppUpdatePlugin.java:2)
com.google.android.play.core.tasks.e.run (e.java:27)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)
```

Fast fix & new plugin release will be highly appreciable. Thanks

**Comment by jonasbark** [comment] 2021-02-03 19:16
Please try to use the plugin from the latest master branch and report back

**Comment by ycv005** [comment] 2021-02-20 18:46
Hey @jonasbark , still found crash even after updating the plugin. Check the below image-

![image](https://user-images.githubusercontent.com/26734819/108605426-03474800-73da-11eb-922e-439b195585a8.png)

**Comment by ycv005** [comment] 2021-02-23 15:31
@jonasbark any update.

**Comment by ycv005** [comment] 2021-02-25 10:39
@jonasbark @mig35 Here is new crash, please tell me a solution

![image](https://user-images.githubusercontent.com/26734819/109141552-ddc49080-7783-11eb-8a36-fef3e7c66a9c.png)

**Comment by jonasbark** [comment] 2021-02-25 10:46
It's the same crash.

Which version are you using? The unreleased one from the master branch or the latest from pub.dev?

**Comment by ycv005** [comment] 2021-02-25 14:46
I am using latest from the pub.dev. below line is in my pubspec.yaml

  `in_app_update: ^1.1.15`
  @jonasbark

**Comment by do4Mother** [comment] 2021-03-25 02:06
i have same issue, any update for this?

**Comment by madhu6264** [comment] 2021-11-16 11:25
same issue here.
<img width="1092" alt="Screenshot 2021-11-16 at 4 44 12 PM" src="https://user-images.githubusercontent.com/10560724/141976998-e5424912-c6d1-490f-bf15-13beefdba508.png">
..

**Comment by yashwp** [comment] 2022-01-13 13:09
@jonasbark Is this package is of any use? You are not even replying!

**Comment by daksh-pokar-shipsy** [comment] 2022-08-01 13:44
Faced 21 crashes in 24 hours for this issue.

**Comment by brunovsiqueira** [comment] 2022-10-10 13:08
Same here. Numerous crashes in the last 24 hours.

**Comment by jonasbark** [comment] 2022-10-10 13:13
Please share some details on the crashes, then.

**Comment by brunovsiqueira** [comment] 2022-10-14 17:22
Here is the crash stacktrace (97 android users affecteds): 
`
Caused by android.content.IntentSender$SendIntentException
android.app.Activity.startIntentSenderForResultInner (Activity.java:5519)
android.app.Activity.startIntentSenderForResult (Activity.java:5487)
androidx.activity.ComponentActivity.startIntentSenderForResult (ComponentActivity.java:631)
com.google.android.play.core.appupdate.zze.startIntentSenderForResult (com.google.android.play:core@@1.10.3:1)
com.google.android.play.core.appupdate.zzf.startUpdateFlowForResult (com.google.android.play:core@@1.10.3:9)
com.google.android.play.core.appupdate.zzf.startUpdateFlowForResult (com.google.android.play:core@@1.10.3:2)
de.ffuf.in_app_update.InAppUpdatePlugin.onActivityResumed$lambda-0 (InAppUpdatePlugin.kt:150)
de.ffuf.in_app_update.InAppUpdatePlugin.$r8$lambda$3XJZpbWv7mcDfk_mt2k7JkkWXKo (InAppUpdatePlugin.kt)
de.ffuf.in_app_update.InAppUpdatePlugin$$InternalSyntheticLambda$0$ae5e87df4e91be3f256e078e509fb3dfba2cf717e3e630af6fcadd7bf346975b$0.onSuccess (InAppUpdatePlugin.java:6)
com.google.android.play.core.tasks.zze.run (com.google.android.play:core@@1.10.3:1)
android.os.Handler.handleCallback (Handler.java:914)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:224)
android.app.ActivityThread.main (ActivityThread.java:7551)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:995)
`

**Comment by ravipiplani** [comment] 2022-11-14 07:11
Here is the exact line where it is failing

`de.ffuf.in_app_update.InAppUpdatePlugin.onActivityResumed$lambda-0 (InAppUpdatePlugin.java:150)`

A possible solution is [https://stackoverflow.com/questions/57290049/java-lang-reflect-invocationtargetexception-while-inappupdate-android-if-retries](https://stackoverflow.com/questions/57290049/java-lang-reflect-invocationtargetexception-while-inappupdate-android-if-retries)

**Comment by venzeo** [comment] 2022-11-15 13:34
![Screenshot 2022-11-15 at 14 33 41](https://user-images.githubusercontent.com/12495851/201932529-c809b790-3cfa-4cd7-9bd4-07762d0f5f9b.jpg)


Fatal Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
       
     Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
       
       Caused by android.content.IntentSender$SendIntentException:
       at android.app.Activity.startIntentSenderForResultInner(Activity.java:5638)
       at android.app.Activity.startIntentSenderForResult(Activity.java:5606)
       at com.google.android.play.core.appupdate.zze.startIntentSenderForResult(com.google.android.play:core@@1.10.3:1)
       at com.google.android.play.core.appupdate.zzf.startUpdateFlowForResult(com.google.android.play:core@@1.10.3:9)
       at com.google.android.play.core.appupdate.zzf.startUpdateFlowForResult(com.google.android.play:core@@1.10.3:2)
       at de.ffuf.in_app_update.InAppUpdatePlugin$onActivityResumed$1.invoke(InAppUpdatePlugin.kt:150)
       at de.ffuf.in_app_update.InAppUpdatePlugin$onActivityResumed$1.invoke(InAppUpdatePlugin.kt:145)
       at de.ffuf.in_app_update.InAppUpdatePlugin.onActivityResumed$lambda$0(InAppUpdatePlugin.kt:145)
       at de.ffuf.in_app_update.InAppUpdatePlugin.$r8$lambda$rxVDuTqUUoc08Ez6X915gCQn_u8(InAppUpdatePlugin.kt)
       at de.ffuf.in_app_update.InAppUpdatePlugin$$InternalSyntheticLambda$0$ae5e87df4e91be3f256e078e509fb3dfba2cf717e3e630af6fcadd7bf346975b$0.onSuccess(InAppUpdatePlugin.java:2)
       at com.google.android.play.core.tasks.zze.run(com.google.android.play:core@@1.10.3:1)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by jonasbark** [comment] 2022-11-16 09:35
Duplicate of https://github.com/jonasbark/flutter_in_app_update/issues/46

**Closed by jonasbark** 2022-11-16 09:35 UTC
